[
	{
		"key": "dbln",
		"value": "%7B%2261587424864783%22%3A%22EqQCW3cl%22%7D",
		"domain": "facebook.com",
		"path": "/login/device-based/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.786Z",
		"lastAccessed": "2026-02-06T10:36:03.787Z"
	},
	{
		"key": "datr",
		"value": "5LmFaWm7OZoKAFEAsMqOSCkb",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.787Z",
		"lastAccessed": "2026-02-06T10:36:03.787Z"
	},
	{
		"key": "sb",
		"value": "5LmFaQPCjXfzRtglRIXGPGnK",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.787Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "m_pixel_ratio",
		"value": "2",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "ps_l",
		"value": "1",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "ps_n",
		"value": "1",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "c_user",
		"value": "61587424864783",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "locale",
		"value": "en_GB",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "pas",
		"value": "61587424864783%3Apryq27dji6",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "vpd",
		"value": "v1%3B674x360x2",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "dpr",
		"value": "2",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "xs",
		"value": "21%3AkFUqxXtTS4EIiw%3A2%3A1770371624%3A-1%3A-1%3A%3AAcxiWAWHu4pAb0CZb4cwEApm7Ia29zMVmCPHg7N6uQ",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "wd",
		"value": "980x1835",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "presence",
		"value": "C%7B%22lm3%22%3A%22g.851960964169187%22%2C%22t3%22%3A%5B%7B%22o%22%3A0%2C%22i%22%3A%22g.2135380467281583%22%7D%5D%2C%22utc3%22%3A1770374104387%2C%22v%22%3A1%7D",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "fr",
		"value": "14LrfXuKxFp6GQ8ER.AWdIwi2X4sbjxnQrvY5Ri-_yJX3QWbit0vxyC9cAJUkyaXlXb-Q.BphcOU..AAA.0.0.BphcPw.AWdO0dfDeFze6kAauJZFKVGGQUA",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "fbl_st",
		"value": "101434096%3BT%3A29506235",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	},
	{
		"key": "wl_cbv",
		"value": "v2%3Bclient_version%3A3070%3Btimestamp%3A1770374128",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-02-06T10:36:03.788Z",
		"lastAccessed": "2026-02-06T10:36:03.788Z"
	}
]
